---
config:
  theme: default
---
sequenceDiagram
  participant Архітектор as Архітектор
  participant Замовник as Замовник
  participant Інженер as Інженер
  participant "3D Модель" as "3D Модель"
  participant "Система перевірки" as "Система перевірки"
  Архітектор ->> "3D Модель": Публікує 3D-модель
  Замовник ->> "3D Модель": Переглядає модель
  Замовник ->> Архітектор: Коментує та затверджує концепт
  Інженер ->> "Система перевірки": Перевіряє конфлікти
  "Система перевірки" -->> Інженер: Результати перевірки
  Інженер ->> Архітектор: Надсилає запит на уточнення
  Архітектор ->> "3D Модель": Випускає оновлену версію